

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: DownloadSecureFile@1
  name: publickey
  inputs:
    secureFile: 'azure_rsa.pub'
    retryCount: '5'
- task: TerraformCLI@0
  inputs:
    command: 'init'
    #commandOptions: '-var client_id=${client_id} -var client_secret=${client_secret} -var ssh_public_key =${publickey}'
    backendType: 'azurerm'
    backendServiceArm: 'azure-resource-service-manager-connection'
    ensureBackend: true
    backendAzureRmResourceGroupName: 'kubernets-cluster'
    backendAzureRmResourceGroupLocation: 'eastus'
    backendAzureRmStorageAccountName: 'storgeaccountk8ctaj'
    backendAzureRmContainerName: 'storgeaccountk8container'
    backendAzureRmKey: 'kubernets-dev.tfstate'
    
# - task: TerraformCLI@0
#   inputs:
#     command: 'validate'
#     commandOptions: '-var client_id=${client_id} -var client_secret=${client_secret} -var ssh_public_key=${publickey}'
#     allowTelemetryCollection: false

- task: TerraformCLI@0
  inputs:
    command: 'apply'
    environmentServiceName: 'azure-resource-service-manager-connection'
    commandOptions: '-var client_id=${client_id} -var client_secret=${client_secret} -var ssh_public_key=${publickey}'
   