# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
    - job: job1
      steps:
      - bash: echo Bulid first job --> job1
    - job: job2
      steps:
        - bash: echo build second job --> job2
- stage: Deploy
  dependsOn: Build
  jobs:
    - job: deployjob
      steps:
        - bash: echo deploy in deploy job       
- stage: QADeploy
  dependsOn: 
   - Build
   - Deploy
  jobs:
    - job: qadeploy
      steps:
      - bash: echo.$job
- stage: ProudDeploy
  dependsOn: 
  - Build
  - Deploy
  jobs:
    - job: prouddeploy
      steps:
      - bash: echo prouddeploy