# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
    - job: job1
      steps:
      - bash: echo Bulid first job --> job1
      - bash: echo $(piplinelevelvariable)
    - job: job2
      steps:
        - bash: echo build second job --> job2
- stage: DevDeploy
  variables:
    environment: Dev
  dependsOn: Build
  jobs:
    - job: deployjob
      steps:
        - bash: echo $(environment)DevDeploy       
- stage: QADeploy
  dependsOn: 
   - Build
   - DevDeploy
   
  jobs:
    - job: qadeploy
      steps:
      - bash: echo $(environment) DevDeploy
- stage: ProudDeploy
  dependsOn: 
  - Build
  - DevDeploy
  - QADeploy
  jobs:
    - job: prouddeploy
      steps:
      - bash:  echo $(environment)DevDeploy